apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.servicename }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: {{ .Values.servicename }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.tport }}
      protocol: {{ .Values.services.protocol }}
  selector:
    app: {{ .Values.app }}
  type: {{ .Values.services.servicetype }}
